default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: forschungsagenda_development

test:
  <<: *default
  database: forschungsagenda_test

production:
  <<: *default
  database: forschungsagenda_production
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
